### PR TITLE
Bumped version to 1.0.4

### PR DESCRIPTION
**Pull request by tekka007**
- support SAMD board def update 1.6.11

### CODE REVIEW

**Comment by tekka007** [comment]
Jenkins: SAMD board def update to 1.6.11 required for verification

**Comment by tbowmo** [comment]
jenkins, build this please

**Comment by tbowmo** [comment]
Jenkins, build this please

**Comment by tbowmo** [comment]
Jenkins, build this please

**Comment by tbowmo** [comment]
Jenkins, build this please

**Comment by tbowmo** [comment]
Jenkins, build this please

**Comment by tbowmo** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
Jenkins, build this please

**Comment by tekka007** [comment]
Jenkins, build this please

**Pull request merged**
